### ISSUE TITLE
Disabling Comment in Sync Loop causes Timeout

### ISSUE THREAD

**Issue by borro0** [geissdoerfer/shepherd#1] opened 2019-08-09 10:22 UTC
Since this log is kinda floading the kernel logs I wanted to comment it out, but that causes a timeout while running record:

https://github.com/geissdoerfer/shepherd/blob/71f0624637a9a549263fcd4fd6a18b1bf8253908/software/kernel-module/src/sync_ctrl.c#L156-L157

Result when code is commented out

command used: sudo python3 cli.py record -l 3
error:
shepherd.sysfs_interface.SysfsInterfaceException: timed out waiting for state running - state is idle

dmesg | grep shepherd:

[  845.073347] shepherd virtio1.rpmsg-shprd.-1.1: timeout waiting for a tx buffer
[  845.080691] shepherd virtio1.rpmsg-shprd.-1.1: rpmsg_send failed: -512

**Comment by geissdoerfer** [comment] 2019-09-10 11:56
Thanks for reporting. I couldn't reproduce the issue, i.e. everything was working even after removing the print statement for me. Anyway, you're right that the messages flood kernel logs. This has been fixed with 7afac7eba10fd3febe215942e3e14bbce26f3214.

**Closed as completed by geissdoerfer** 2019-09-10 11:56 UTC
